apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-there-deployment
spec:
  selector:
    matchLabels:
      app: hello-there
  template:
    metadata:
      labels:
        app: hello-there
    spec:
      containers:
      - name: hello-there
        image: jtrouth/hello-there:latest
        resources:
          requests:
            memory: "8Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000 # This must match the port defined in the configmap.yaml file.
        # Add an environment variable to specify the application port
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                key: PORT
                name: hello-there-config
