apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-there-deployment
spec:
  selector:
    matchLabels:
      app: hello-there
  template:
    metadata:
      labels:
        app: hello-there
    spec:
      containers:
      - name: hello-there
        image: jtrouth/hello-there:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
